
#ifndef CONVERQIMAGEORCVMAT_EXPORT_H
#define CONVERQIMAGEORCVMAT_EXPORT_H

#ifdef CONVERQIMAGEORCVMAT_STATIC_DEFINE
#  define CONVERQIMAGEORCVMAT_EXPORT
#  define CONVERQIMAGEORCVMAT_NO_EXPORT
#else
#  ifndef CONVERQIMAGEORCVMAT_EXPORT
#    ifdef converQimageOrCvMat_EXPORTS
        /* We are building this library */
#      define CONVERQIMAGEORCVMAT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CONVERQIMAGEORCVMAT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CONVERQIMAGEORCVMAT_NO_EXPORT
#    define CONVERQIMAGEORCVMAT_NO_EXPORT 
#  endif
#endif

#ifndef CONVERQIMAGEORCVMAT_DEPRECATED
#  define CONVERQIMAGEORCVMAT_DEPRECATED __declspec(deprecated)
#endif

#ifndef CONVERQIMAGEORCVMAT_DEPRECATED_EXPORT
#  define CONVERQIMAGEORCVMAT_DEPRECATED_EXPORT CONVERQIMAGEORCVMAT_EXPORT CONVERQIMAGEORCVMAT_DEPRECATED
#endif

#ifndef CONVERQIMAGEORCVMAT_DEPRECATED_NO_EXPORT
#  define CONVERQIMAGEORCVMAT_DEPRECATED_NO_EXPORT CONVERQIMAGEORCVMAT_NO_EXPORT CONVERQIMAGEORCVMAT_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef CONVERQIMAGEORCVMAT_NO_DEPRECATED
#    define CONVERQIMAGEORCVMAT_NO_DEPRECATED
#  endif
#endif

#endif /* CONVERQIMAGEORCVMAT_EXPORT_H */
