
#ifndef IMAGECOMPARATOR_EXPORT_H
#define IMAGECOMPARATOR_EXPORT_H

#ifdef IMAGECOMPARATOR_STATIC_DEFINE
#  define IMAGECOMPARATOR_EXPORT
#  define IMAGECOMPARATOR_NO_EXPORT
#else
#  ifndef IMAGECOMPARATOR_EXPORT
#    ifdef imageComparator_EXPORTS
        /* We are building this library */
#      define IMAGECOMPARATOR_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define IMAGECOMPARATOR_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef IMAGECOMPARATOR_NO_EXPORT
#    define IMAGECOMPARATOR_NO_EXPORT 
#  endif
#endif

#ifndef IMAGECOMPARATOR_DEPRECATED
#  define IMAGECOMPARATOR_DEPRECATED __declspec(deprecated)
#endif

#ifndef IMAGECOMPARATOR_DEPRECATED_EXPORT
#  define IMAGECOMPARATOR_DEPRECATED_EXPORT IMAGECOMPARATOR_EXPORT IMAGECOMPARATOR_DEPRECATED
#endif

#ifndef IMAGECOMPARATOR_DEPRECATED_NO_EXPORT
#  define IMAGECOMPARATOR_DEPRECATED_NO_EXPORT IMAGECOMPARATOR_NO_EXPORT IMAGECOMPARATOR_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef IMAGECOMPARATOR_NO_DEPRECATED
#    define IMAGECOMPARATOR_NO_DEPRECATED
#  endif
#endif

#endif /* IMAGECOMPARATOR_EXPORT_H */
